### ISSUE TITLE
Some errors in the released dataset?

### ISSUE THREAD

**Issue by whr94621** [Hi-archers/MLaKE#1]
See https://github.com/Hi-archers/MLaKE/blob/main/dataset/multi_hop/mcqa/new_zh_mcqa.json#L91

I think the University of Cambridge is not located in United States?

**Comment by whr94621** [comment]
Sorry I get messed up... This is the benchmark after knowledge editing...

**Comment by Hi-archers** [comment]
Thank you for your attention to our work. It was an oversight on our part, and we will soon update the README to explain how to use our benchmark.
